Image.new("space_bg", "Assets/space_bg.png")
Image.new("pregame1", "Assets/pregame1.png")
Image.new("pregame2", "Assets/pregame2.png")
Image.new("rocket", "Assets/rocket.png")
Image.new("asteroid", "Assets/asteroid.png")
Image.new("Ahh_bg", "Assets/Intro.png")
--Font.new("Font","Assets/Bersan-vnlvE.tff",17)
NewFont = love.graphics.newFont("Assets/Bersan-vnlvE.ttf", 17)
