Image.new("space_bg", "Assets/space_bg.png")
Image.new("pregame1", "Assets/pregame1.png")
Image.new("pregame2", "Assets/pregame2.png")
Image.new("rocket", "Assets/rocket.png")
Image.new("asteroid", "Assets/asteroid.png")
Image.new("Ahh_bg", "Assets/Intro.png")
--Font.new("Font","Assets/Bersan-vnlvE.tff",17)
NewFont = love.graphics.newFont("Assets/Bersan-vnlvE.ttf", 17)
bgm = love.audio.newSource("Assets/ast_soundtr1.wav", "stream")
introm = love.audio.newSource("Assets/intro_music.wav", "stream")
die = love.audio.newSource("Assets/dies_audio.wav", "stream")
hit = love.audio.newSource("Assets/hit.wav", "static")
win = love.audio.newSource("Assets/win.wav", "stream")
Image.new("winbg", "Assets/winbg.png")